---
micronaut:
  application:
    name: gateway
  server:
    port: 8080
    cors:
      enabled: true
---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"
      writer:
        header:
          enabled: true
      propagation:
        enabled: true
        service-id-regex: "inventory"
  multitenancy:
    propagation:
      enabled: true
      service-id-regex: 'inventory'
    tenantresolver:
      subdomain:
        enabled: true
    tenantwriter:
      httpheader:
        enabled: true
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
---